# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: create-wazuh-packages

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New Version'
        required: true
      username:
        description: 'Username'
        required: true
      password:
        description: 'Password'
        required: true        
      email:
        description: 'Email'
        required: true 
jobs:
  setup-wazuh-kibana-app:
    name: Run setup environment wazuh kibana app
    runs-on: ubuntu-18.04
    steps:
     - name: Step 01 - Set up environment variables
       run: |
        echo "WAZUH_HEAD_BRANCH=feature/create-package-4.2.2-7.13.4" >> $GITHUB_ENV
        mkdir packages
     - name: Step 02 - Download Project wazuh-packages 
       uses: actions/checkout@v2
       with:
        repository: wazuh/wazuh-packages
        ref: 'v4.2.2'
        path: wazuh-packages
     - name: Step 03 - Building package
       run: |
        cd $GITHUB_WORKSPACE/wazuh-packages/wazuhapp
        echo fixing command...
        sed -i -e 's/'\|' cut -d \"\/\" \-f2//g' ./generate_wazuh_app.sh 
        echo run command...
        ./generate_wazuh_app.sh -b ${{ env.WAZUH_HEAD_BRANCH }} -s $GITHUB_WORKSPACE/packages -r 1
        cd $GITHUB_WORKSPACE/packages
        ls -a
     - name: Archive packages
       uses: actions/upload-artifact@v2
       with:
        name: wazuh-packages
        path: packages/*
